### ISSUE TITLE
设置value后日历并没有更新到当天的界面

### ISSUE THREAD

**Issue by jumplee** [tuhe32/vue-jLunar-datePicker#1]
如题

**Comment by jumplee** [comment]
![image](https://user-images.githubusercontent.com/1783964/31764889-2819c8ac-b488-11e7-99f9-469f95d11bed.png)

**Comment by jumplee** [comment]
安装github最新版本问题解决，npm仍然只能装1.0版本

**Comment by tuhe32** [comment]
请使用淘宝的cnpm来安装，您的问题我正在检查

**Comment by jumplee** [comment]
![image](https://user-images.githubusercontent.com/1783964/31810399-41dece7c-b541-11e7-8ee0-64d475e3ff70.png)
已经是淘宝源
仍然只能装1.0

**Comment by king1903** [comment]
@jumplee  最新版本号为：2.2.2，bug已更新。
如果是赋值，组件是能识别的，如果是手动输入需要回车确认才能识别。
package.json中更新版本号后重新安装试试，cnpm install

**Comment by king1903** [comment]
@jumplee 版本已更新至2.2.2，bug已更新。如果是赋值，组件是能识别的，如果是手动输入需要回车确认才能识别。
