### ISSUE TITLE
农历数据有问题

### ISSUE THREAD

**Issue by shoushuaigu** [tuhe32/vue-jLunar-datePicker#5]
您的阳历1991.05.01是十六，但应该是十七，阳历1991.09.14和阳历1991.09.15分别为农历初六和初八，以至于1991.05.01~1991.09.15之前的农历错了一天，望修改或提供个修改方案，谢谢

**Comment by king1903** [comment]
已更新,之前没有时间看,不好意思啦,虽然问题已关闭,我还是重新提交了代码,之前的问题在于通过js获取农历信息的时候用的moment读取的时间是当天的15:00:00,例如界面上看到的是1991.05.01,实际是1991.04.30 15:00:00,所以显示的农历日期是错误的.将JDatePicker.vue 721行的改为:lDate: JDatePickerScript.calendar.getLunar(start.clone().format('YYYY-MM-DD')),即可.
