### ISSUE TITLE
“除夕”多次出现，几乎每1~2个月一次

### ISSUE THREAD

**Issue by YFengFly** [tuhe32/vue-jLunar-datePicker#6]
1.获取来源：
npm vue-jlunar-datepicker v2.3.0
2.异常现象
RT，“除夕”多次出现，几乎每1~2个月一次
然而Demo页面无此问题。好在Demo有map，经查，Demo使用的为 commit 00bb0bb09e0e264643c1a040529c26eefa3bb5cc 之前的版本。将jDatePicker.js单纯的覆盖为老版本，无此现象。

精力与能力有限，尚未查到其原因，望能修正。

![image](https://user-images.githubusercontent.com/11311708/57306725-ec0c6d00-7115-11e9-9739-ce8908f352cf.png)

**Comment by king1903** [comment]
感谢指正.代码行534,除夕条件未设置优先级造成代码逻辑错误.已修正.

**Comment by tuhe32** [comment]
已修复
